doc.type.html
script
filename=covidstrings17gamecode.js
java.awt graphics
this.img=document.createelement(covid)
img.src=http://www.google.com/intl/en_com/images/logo_plain.png
src=document getelementbyid(header)
src.appendchild(this.img)
<div id=header></div>
audio=new audio (audio_file mp3)
audio.play 
jbutton random button
new jbutton (set random color)
private final j button option button=
new j button (change color)
public fun with graphics()
jpanel color panel=new j panel();
this add (color.panel,border layout.center)
jpanel button panel=
new j panel (flowlayout.center)
buttonpanel.add(randombutton);
random.button add actionlistener(new action listener()
override 
public actionperformed(actionevent e)
random r= newrandom();
colorpanel.setbackground(new color(rnextint(13),)(rnextint(13),)(rnextint(13),)(rnextint(13),)(rnextint(13),)(rnextint(13),)(rnextint(13),)(rnextint(13),)(rnextint(13),)(rnextint(13),)(rnextint(13),)(rnextint(13),)((rnextint(13)))
buttonpanel.add(optionbutton);
optionbutton.add actionlistener(new action listener()
override 
public actionperformed(actionevent e)
color m=jcolorchooser.showdialog(funwithgraphics.this,)
if(multi!=null)
color panel set.background(multi)
this.add(buttonpanel, borderlayout.south)
public static main(string [] args){
jframe f = new covid strings17()
f.set title(covid strings17)
f.set default closeoperation(jframe.exit_on_close);
f.setsize
f.set visible(true);
<label id=lblscore>zero</label>
score=zero
if (mult == x*y)
[non-concatenated]
score+=ten
else:
score-=ten
if (mult ==x*y)
[concatenated]
score+=twenty
else:
score-=twenty
lblscore=document.getelementbyid(lblscore)
lbl.score.innerHTML=score
public actionperformed(action event e) 
system.out print.in (next button clicked)
frame.add(next button);
frame set visible true
object{a:one,b:two,c:three,d:four,e:five,f:six,g:seven,h:eight}
keys object keys(team)
entries object entries(obj);
value object= [team color]
covidstringsteamlist17=[yellow,green,red,magenta,black,white,blue,violet]
covid strings phraselist17=[long covid is so serious it might impact exercise]
which makes it more concerning that ron desantiss surgeon general called covid shots the antichrist
hydroxychloroquine killing17 thousand people is even worse than trumps claim that desantis was vaxing everything
silent invasion by dr. deborah birx shows how silent trump may just have been during covid
perhaps this explains the appeal behind deathto2020 and death to2021
according to town and country the most accurate pandemic movie being the andromeda strain might be prescient3 million years from now
here in the present the holidays and covid still exist in the minds of many americans
the risk of coinfection for flu and covid is low but can lowered with vaccination
concatenated strings
dont+be+fooled+into+thinking+hv1+is+gone
covid+is+not+responsible+for+every+perception+of+people+being+sick
cnns+coronavirus+facts+and+fears+town+hall+can+help+parse+information
one+question+would+be+whether+america+or+europes+covid+response+was+better
another+question+might+involve+gain+of+function+research
a+third+question+might+be+how+much+discord+did+the+eris+variant+cause?
a+final+question+might+be+how+will+we+remember+this?
one+hopes+there+will+be+great+expectations+on+this+front]
covidstrings17mathproblemslist=[if78 percent of americans view death to2020s theme favorably how many dont?, if71 percent strongly approve how many are mild?,if the margin of error is7.5percent what is the range?,If+Only+20+Percent+Strongly+Agree+How+Many+Are+Mild?,If+The+Margin+Of+Error+Is+2.023+Percent+What+Is+The+Range?,If+63+Percent+Trusted+cnn+with+covid+information+how+many+didnt?,if+56+percent+strongly+trust+cnn+what+percent+is+mild?,if+the+margin+of+error+is+2and5/6+percent+what+is+the+range?]
Covid Strings Multiple Choice List17=[1:A Hydroxychloroquine B Avidiivka C Ann Coulter Voting For Joe Biden D The GOP Going Down With The Ship,2:A Covid B The Tide Pod Challenge C Trump J6 Drama D People Believing Trump Is On The Right Side Of The14th Amendment,3: A Stacy Abrams B Ron DeSantis C Andrew Gillum D Alvin Bragg,4:A JN1 B Covid C HV1 D The Jeffrey Epstein Scandal,5:A Long Covid B Sick Leave Policies C Death D RSV,6: A mike johnson lies b fears c high hopes d john adams14th amendment,7 a silent b violent night c british d mexican,
8: A Canada B Europes C Asias D Zealandias,9:A Significance B Victorianesqueness C Appeal D Power Of Jelly Roll,10:A What It Would Be Like To Live On Mercury B Gain Of Function Research C Putin Saying He Is Unrecognizable D Whether Gen Z Elects Joe Biden Again,11:A Milkcomeda B Andromeda C Khazmat D Trumpchurian,12:A Easy B Second C Third D Last,13:A Moon B Present C Future D A Storage Facility For Old US Aircraft,14:A Forget This B Cryogenically Freeze C Remember This  D Believe In Santa Claus,
15:A Coinfection B Voting For Trump Being A Trap C Putin And Xi Carrying Nuclear Footballs D The Proud Boys Being Held Accountable,16:A Thanksgiving B Easter C Back To School D Christmas,17:A Plenty Of Primary Sources B Great Expectations C Jimmy Fallon Christmas Songs D New NASA Moon Missions,18:A Christmas B Halloween C4th Of July D Juneteenth,19:A The Virus B Americas Founding Fathers C The Supreme Court On January6th D Nikki Haley,20:A2049 B2075 C2020 D2077,21:A TV Series B Covid Archives C TV Shows About B117 In America D Jokes About How Bad Russias Air Defenses Are,
22:A January6th B Being Disqualified Under The14th Amendment C The Idea Of America As Great Country D The Star Wars Franchise,23:A Christmas Songs B Fall Songs C The Courts Keeping Trump From Staying In Office Illegally D Biden Forgiving Student Loans]
Covid Strings SentenceList17=[21Pilots Christmas Saves The Year Is Emblematic Of2020,Not All Christmas Songs Were About Covid,Covid Great Expectations Differ Depending On If Youre The Virus Or A Person,Like Trumps Efforts To Delay Being Disqualified Under The14th Amendment Covid Is Not Gone,The One Exception To Wanting2020 To Be Over Is Knowing The Top Christmas Songs Of2020 ,People+Would+Never+Forget+That+2020+Was+Covids+First+Year+In+America,Hopefully+There+Will+Be+Plenty+Of+Covid+Archives+In+The+Years+To+Come]
Userin.Select Team
Import Meta.
Class MyClass
Constructor (Non-Concatenated)
Return Category
If Category==Math Problem:
Prompt
Log
Else:
Select From Multiple Choice
If Problem=Multiple Choice 
Select From Multiple Choice
Else
Prompt 
Log
Myclass=New.Myclass(Concatenated)
Return Category
If Category==Math Problem:
Prompt
Log
Else:
Select From Multiple Choice
If Problem=Multiple Choice 
Select From Multiple Choice
Else
Prompt 
Log
Import Syntax 
Substring(Start,End)
Userin.Multiple Choice
If SelectedAnswer==Correct Answer:
Return True
Else:
Return False
If Selectedanswer=Not Correct
Return False
Else 
Return True






