doc.type html
script
html
head
utf8
viewportcontent=width=device-width,initial-scale=one
title covid strings17 first round bracket
div id bracket class bracket div
script src bracket.js
link rel= stylesheet href=css
head
body
bracket-container{}
matchup
solid zero;
padding 
text align center 
filename=covid strings17 first round.js
first round=(highest overall seed ,second highest seed third highest seed first middle seed, second middle seed,  third lowest seed ,second lowest seed,lowest overall seed)
highest overall seed = 1 seed
second highest seed=2 seed
third highest seed=3 seed
firstmiddleseed=4seed
second middle seed = 5 seed
third lowest seed= 6 seed
second lowest seed = 7 seed
lowest overall seed = 8 seed
covidstringsteamlist17=[yellow,green,red,magenta,black,white,blue,violet]
matchup1=(blue versus green)
matchup2=(white versus red)
matchup3=(violet versus yellow)
matchup4=(black versus magneta)
bracket = getelementbyid(bracket);
document.createelement 
matchupdiv.classname=(matchup)
matchupdiv.inner html =[matchup]
rounddiv.appendchild(matchup)
for(i in covid strings first round)
round div=create element
round div class name=covid strings17 first round
bracket.appendchild(round div)
if (event.target.covid strings seed list.contains(matchup))
event.target.covid strings seed list.toggle
else:
addmatchup
java util.scanner
java.util
questions[]questions=
question1
question2
question3
question4
question5
question6
question7
question8
question9
question10
question11
question12
question13
question14
if selectedanswer==correct:
return true
else:
return false
advancingteam=slice(currentteams)
declarewinner
result=declarewinner(matchup1)
if green score>=forty:
console.log(green peacemakers win)
else:
console.log(blue curve crushers win)
result=declarewinner(matchup2)
if red score>=forty:
console.log(red protein spikers win)
else:
console.log(white transit angels win)
result=declarewinner(matchup3)
if yellow score>=forty:
console.log(yellow moxie wins)
else:
console.log(violet relivers win)
result=declarewinner(matchup4)
if magenta score=forty:
console.log(magenta magnetizers win)
else:
console.log(black night riders win)
return filename
