doc.type.html
script
filename=covidstrings17gamecode.js
java.awt graphics
this.img=document.createelement(covid)
img.src=http://www.google.com/intl/en_com/images/logo_plain.png
src=document getelementbyid(header)
src.appendchild(this.img)
<div id=header></div>
audio=new audio (audio_file mp3)
audio.play 
random button
new button (set random color)
private final j button option button=
new  button (change color)
public fun with graphics()
color panel=new j panel();
add (panel,center)
button panel
new panel (flowlayout.center)
buttonpanel.add(randombutton);
random.button add actionlistener(new action listener)
override 
public actionperformed(actionevent e)
random r= newrandom();
colorpanel.setbackground(new color(rnextint(13),)(rnextint(13),)(rnextint(13),)(rnextint(13),)(rnextint(13),)(rnextint(13),)(rnextint(13),)(rnextint(13),)(rnextint(13),)(rnextint(13),)(rnextint(13),)(rnextint(13),)((rnextint(13)))
num teams
total players= players per team
if players per team=zero
return zero
else 
return math floor total players/players per team
Teamsgrouping=(rnextint8)(rnextint8)(rnextint8)(rnextint8)(rnextint8)(rnextint8)(rnextint8)
buttonpanel.add(optionbutton);
optionbutton.add actionlistener(new action listener)
override 
public actionperformed(actionevent e)
color m=jcolorchooser.showdialog(funwithgraphics.this)
if(multi!=null)
color panel set.background(multi)
this.add(buttonpanel, borderlayout.south)
public static main(string [] args){
jframe f = new covid strings17()
f.set title(covid strings17)
f.set default closeoperation(jframe.exit_on_close);
f.setsize
f.set visible(true);
<label id=lblscore>zero</label>
score=zero
if (mult == x*y)
[non-concatenated]
score+=ten
else:
score-=ten
if (mult ==x*y)
[concatenated]
score+=twenty
else:
score-=twenty
lblscore=document.getelementbyid(lblscore)
lbl.score.innerHTML=score
public actionperformed(action event e) 
system.out print.in (next button clicked)
frame.add(next button);
frame set visible true
object{a:one,b:two,c:three,d:four,e:five,f:six,g:seven,h:eight}
keys object keys(team)
entries object entries(obj);
value object= [team color]
covidstringsteamlist17=[yellow moxie,green peacemakers,red protein spikers,magenta magnetizers ,black night riders ,white transit angels,blue curve crsuhers,violet relivers]
covid strings phraselist17=[ non-concatenated strings "long covid is so serious it might impact exercise"]
"which makes it more concerning that ron desantiss surgeon general called covid shots the antichrist"
"hydroxychloroquine killing17 thousand people is even worse than trumps claim that desantis was vaxing everything"
"silent invasion by dr. deborah birx shows how silent trump may just have been during covid"
"perhaps this explains the appeal behind deathto2020 and death to2021"
"according to town and country the most accurate pandemic movie being the andromeda strain might be prescient3 million years from now"
"here in the present the holidays and covid still exist in the minds of many americans"
"the risk of coinfection for flu and covid is low but can lowered with vaccination"
concatenated strings
"dont"+"be"+"fooled"+"into"+"thinking"+"hv1"+"is"+"gone"
"covid"+"is"+"not"+"responsible"+"for"+"every"+"perception"+"of"+"people"+"being"+"sick"
"cnns"+"coronavirus"+"facts"+"and"+"fears"+"town"+"hall"+"can"+"help"+"parse"+"information"
"one"+"question"+"would"+"be"+"whether"+"america"+"or"+"europes"+"covid"+"response"+"was"+"better"
"another"+"question"+"might"+"involve"+"gain"+"of"+"function"+"research"
"a"+"third"+"question"+"might"+"be"+"how"+"much"+"discord"+"did"+"the"+"eris"+"variant"+"cause"?
"a"+"final"+"question"+"might"+"be"+"how"+"will"+"we"+"remember"+"this"?
"one"+"hopes"+"there"+"will"+"be"+"great"+"expectations"+"on"+"this"+"front"]
covidstrings17mathproblemslist=[ non-concatenated "if78 percent of americans view death to2020s theme favorably how many dont"?, "if71 percent strongly approve how many are mild"?,"if the margin of error is7.5percent what is the range"?,
concatenated "if"+"only"+"20"+"percent"+"strongly"+"agree"+"how"+"many"+"are"+"mild"?,"if"+"the"+"margin"+"of"+"error"+"is"+"2.023"+"percent"+"what"+"is"+"the"+"range"?,"if"+"63"+"percent"+"trusted"+"cnn"+"with"+"covid"+"information"+"how"+"many"+"didnt"?,"if"+"56"+"percent"+"strongly"+"trust"+"cnn"+"what"+"percent"+"is"+"mild"?,"if"+"the"+"margin"+"of"+"error"+"is"+"2and5/6"+"percent"+"what"+"is"+"the"+"range"?]
covid strings multiple choice list17=[1:a hydroxychloroquine b avidiivka c ann coulter voting for joe biden d the gop going down with the ship,2:a covid b the tide pod challenge c trump j6 drama d people believing trump is on the right side of the14th amendment,3:a stacy abrams b ron desantis C Andrew Gillum D Alvin Bragg,4:a jn1 b covid c hv1 d the jeffrey epstein scandal,5:a long covid b sick leave policies c death d rsv,6: a mike johnson lies b fears c high hopes d john adams14th amendment,7 a silent b violent night c british d mexican,
8:a canada b europes c asias d zealandias,9: a significance b victorianesqueness c appeal d power of jelly roll,10:a what it would be like to live on mercury b gain of function research c putin saying he is unrecognizable d whether gen z elects joe biden again,11:a milkcomeda b andromeda c khazmat d trumpchurian,12:a easy b second c third d last,13:a moon b present c future d a storage facility for old us aircraft,14:a forget this b cryogenically freeze c remember this  d believe in santa claus,
15:a coinfection b voting for trump being a trap c putin and xi carrying nuclear footballs d the proud boys being held accountable,16:a thanksgiving b easter c back to school d christmas,17:a plenty of primary sources b great expectations c jimmy fallon christmas songs d new nasa moon Missions,18:A Christmas b halloween c 4th of july d juneteenth,19:a the virus b americas founding fathers c the supreme court on january6th d nikki haley,20:a2049 b2075 c2020 d2077,21:a tv series b covid archives c tv shows about b117 in america d jokes about how bad russias air defenses are,
22:a january6th b being disqualified under the14th amendment c the idea of america as great country d the star wars franchise,23:a christmas songs b fall songs c the courts keeping trump from staying in office illegally d biden forgiving student loans]
covidstringssentencelist17=["21pilots christmas saves the year is emblematic of2020","not all christmas songs were about covid","covid great expectations differ depending on if youre the virus or a person","like trumps efforts to delay being disqualified under the14th amendment covid is not gone","the one exception to wanting2020 to be over is knowing the top christmas songs of2020","people"+"would"+"never"+"forget"+"that"+"2020"+"was"+"covids"+"first"+"year"+"in"+"america","hopefully"+"there"+"will"+"be"+"plenty"+"of"+"covid"+"archives"+"in"+"the"+"years"+"to"+"come"]
userin.select team
import meta.
class myclass
constructor (non-concatenated)
return category
if category==math problem:
prompt
log
else:
select from multiple choice
if problem=multiple choice 
select from multiple choice
else
prompt 
log
myclass=new.myclass(concatenated)
return category
if category==math problem:
prompt
log
else:
select from multiple choice
if problem=multiple choice 
select from multiple choice
else
prompt 
log
import syntax 
substring(start,end)
userin.multiple choice
if selectedanswer==correct answer:
return true
else:
return false
if selectedanswer=not correct
return false
else 
return true
answer checker
scanner=new scanner(system.in)
string correct answer
string useranswer=scanner.nextline()
if useranswer.equals(correctanswer)
system.out.print.in(correct)
else:
system.out.printin(incorrect)
scanner.close
check winner:
if winner==true:
log(the winner is)
if winner==false:
log(no winner yet) 
if users team wins covid strings17 
console log users team wins covid strings17 
else
return game over
return filename





