doc.type.html
html lang en 
script
header=document create.element(header)
header.style.backgroundcolor=#4caf50
header.style.color=’white’
header.style.padding=’10px’
header.style.textalign=’center’
header.style.text.fontsize=’24px’
header.textcontent=’welcome to covid strings17’
document appendchild(header)
<header.html>
heading variables 
the heading numbers that determine where each heading and subheading go 
heading1=game code overview
heading2=background functions
heading3=game code part1
heading4=phrases
heading5=math problems
heading6=multiple choice questions
heading7=sentences
heading8=game code part2 
heading9=answer checker
heading10=winner checker
subheading1=polling problems
subheading2=answer scanner
filename=covidstrings17.js
<header.html>
game code overview
an outline of the game code for covid strings17
java.awt graphics
this.img=document.createelement(covid)
img.src=http://www.google.com/intl/en_com/images/logo_plain.png
src=document getelementbyid(header)
src.appendchild(this.img)
<div id=header></div>
audio=new audio (audio_file mp3)
audio.play 
random button
new button (set random color)
option button
new  button (change color)
public fun with graphics()
color panel=new  panel();
add (panel,center)
button panel
new panel (flowlayout.center)
buttonpanel.add(randombutton);
random.button add actionlistener(new action listener)
override 
public actionperformed(actionevent e)
random r= newrandom();
<header.html>
background functions
the functions that lead into the background that are the first things the user will experience
colorpanel.setbackground(new color(rnextint(13),)(rnextint(13),)(rnextint(13),)(rnextint(13),)(rnextint(13),)(rnextint(13),)(rnextint(13),)(rnextint(13),)(rnextint(13),)(rnextint(13),)(rnextint(13),)(rnextint(13),)((rnextint(13)))
num teams
total players= players per team
if players per team=zero
return zero
else 
return math floor total players/players per team
teamsgrouping=(rnextint8)(rnextint8)(rnextint8)(rnextint8)(rnextint8)(rnextint8)(rnextint8)
buttonpanel.add(optionbutton);
optionbutton.add actionlistener(new action listener)
override 
<header.html>
game code part1
part1 of game code for covid strings17(value object[team-color]-desired color green)
public actionperformed(actionevent e)
color m=jcolorchooser.showdialog(funwithgraphics.this)
if(multi!=null)
color panel set.background(multi)
this.add(buttonpanel, borderlayout.south)
public static main(string [] args){
jframe f = new covid strings17()
f.set title(covid strings17)
f.set default closeoperation(exit_on_close);
f.setsize
f.set visible(true);
<label id=lblscore>zero</label>
score=zero
if (mult == x*y)
[non-concatenated]
score+=ten
else:
score-=ten
if (mult ==x*y)
[concatenated]
score+=twenty
else:
score-=twenty
lblscore=document.getelementbyid(lblscore)
lbl.score.innerHTML=score
public actionperformed(action event e) 
system.out print.in (next button clicked)
frame.add(next button);
frame set visible true
object{a:one,b:two,c:three,d:four,e:five,f:six,g:seven,h:eight}
keys object keys(team)
entries object entries(obj);
value object= [team color]
covidstringsteamlist17=[yellow moxie,green peacemakers,red protein spikers,magenta magnetizers ,black night riders ,white transit angels,blue curve crsuhers,violet relivers]
<header.html>
phrases
phrases that involve both non-concatenated and concatenated strings 
covid strings phraselist17=[ non-concatenated strings "long covid is so serious it might impact exercise"]
"which makes it more concerning that ron desantiss surgeon general called covid shots the antichrist"
"hydroxychloroquine killing17 thousand people is even worse than trumps claim that desantis was vaxing everything"
"silent invasion by dr. deborah birx shows how silent trump may just have been during covid"
"perhaps this explains the appeal behind deathto2020 and death to2021"
"according to town and country the most accurate pandemic movie being the andromeda strain might be prescient3 million years from now"
"here in the present the holidays and covid still exist in the minds of many americans"
"the risk of coinfection for flu and covid is low but can lowered with vaccination"
concatenated strings
"dont"+"be"+"fooled"+"into"+"thinking"+"hv1"+"is"+"gone"
"covid"+"is"+"not"+"responsible"+"for"+"every"+"perception"+"of"+"people"+"being"+"sick"
"cnns"+"coronavirus"+"facts"+"and"+"fears"+"town"+"hall"+"can"+"help"+"parse"+"information"
"one"+"question"+"would"+"be"+"whether"+"america"+"or"+"europes"+"covid"+"response"+"was"+"better"
"another"+"question"+"might"+"involve"+"gain"+"of"+"function"+"research"
"a"+"third"+"question"+"might"+"be"+"how"+"much"+"discord"+"did"+"the"+"eris"+"variant"+"cause"?
"a"+"final"+"question"+"might"+"be"+"how"+"will"+"we"+"remember"+"this"?
"one"+"hopes"+"there"+"will"+"be"+"great"+"expectations"+"on"+"this"+"front"]
string manager{non-concatenated}
insert string (entity,string)
entity.element.text=string
string manager insert string
string manager{concatenated}
insert string (entity,string)
entity.element.text=string
string manager insert string
string=””
for string in covid strings phrase list17 
select characters
edit diffuse property
desired color=green
<header.html>
math problems
covid related math problems that will appear in covid strings17
covidstrings17mathproblemslist=[ non-concatenated strings "if78 percent of americans view death to2020s theme favorably how many dont"?, "if71 percent strongly approve how many are mild"?,"if the margin of error is7.5percent what is the range"?,]
concatenated strings ["if"+"only"+"20"+"percent"+"strongly"+"agree"+"how"+"many"+"are"+"mild"?,"if"+"the"+"margin"+"of"+"error"+"is"+"2.023"+"percent"+"what"+"is"+"the"+"range"?,"if"+"63"+"percent"+"trusted"+"cnn"+"with"+"covid"+"information"+"how"+"many"+"didnt"?,"if"+"56"+"percent"+"strongly"+"trust"+"cnn"+"what"+"percent"+"is"+"mild"?,"if"+"the"+"margin"+"of"+"error"+"is"+"2and5/6"+"percent"+"what"+"is"+"the"+"range"?]
string manager{non-concatenated}
insert string (entity,string)
entity.element.text=string
string manager insert string
string manager{concatenated}
insert string (entity,string)
entity.element.text=string
string manager insert string
string=””
for string in covid strings17 math problems list 
select characters
edit diffuse property
desired color=green
public static main(string []args)
int number
number=number*2
system.out print in (“the number is“+number)
<subheading.html>
polling problems
math problems that involve the use of polls
polling function (exact,number)
console log (exact:${exact},number:${number},
if polling function log== (exact,number)
return true
else:
return false
if polling function log==(number,exact)
return false
else:
return true  
for math problems in covid strings math problem list 
if math problem==polling percent:
subtract exact from 100
else:
remain 
if math problem==margin of error:
add and subtract exact number
else:
remain 
<header.html>
multiple choice questions 
multiple choice questions and answers that will appear in covid strings17
covid strings multiple choice list17=[1:a hydroxychloroquine b avidiivka c ann coulter voting for joe biden d the gop going down with the ship,2:a covid b the tide pod challenge c trump j6 drama d people believing trump is on the right side of the14th amendment,3:a stacy abrams b ron desantis C Andrew Gillum D Alvin Bragg,4:a jn1 b covid c hv1 d the jeffrey epstein scandal,5:a long covid b sick leave policies c death d rsv,6: a mike johnson lies b fears c high hopes d john adams14th amendment,7 a silent b violent night c british d mexican,
8:a canada b europes c asias d zealandias,9: a significance b victorianesqueness c appeal d power of jelly roll,10:a what it would be like to live on mercury b gain of function research c putin saying he is unrecognizable d whether gen z elects joe biden again,11:a milkcomeda b andromeda c khazmat d trumpchurian,12:a easy b second c third d last,13:a moon b present c future d a storage facility for old us aircraft,14:a forget this b cryogenically freeze c remember this  d believe in santa claus,
15:a coinfection b voting for trump being a trap c putin and xi carrying nuclear footballs d the proud boys being held accountable,16:a thanksgiving b easter c back to school d christmas,17:a plenty of primary sources b great expectations c jimmy fallon christmas songs d new nasa moon Missions,18:A Christmas b halloween c 4th of july d juneteenth,19:a the virus b americas founding fathers c the supreme court on january6th d nikki haley,20:a2049 b2075 c2020 d2077,21:a tv series b covid archives c tv shows about b117 in america d jokes about how bad russias air defenses are,
22:a january6th b being disqualified under the14th amendment c the idea of america as great country d the star wars franchise,23:a christmas songs b fall songs c the courts keeping trump from staying in office illegally d biden forgiving student loans]
<header.html>
sentences
covid related sentences that will appear in covid strings17
covidstringssentencelist17=["21pilots christmas saves the year is emblematic of2020","not all christmas songs were about covid","covid great expectations differ depending on if youre the virus or a person","like trumps efforts to delay being disqualified under the14th amendment covid is not gone","the one exception to wanting2020 to be over is knowing the top christmas songs of2020","people"+"would"+"never"+"forget"+"that"+"2020"+"was"+"covids"+"first"+"year"+"in"+"america","hopefully"+"there"+"will"+"be"+"plenty"+"of"+"covid"+"archives"+"in"+"the"+"years"+"to"+"come"]
string manager{non-concatenated}
insert string (entity,string)
entity.element.text=string
string manager insert string
string manager{concatenated}
insert string (entity,string)
entity.element.text=string
string manager insert string
string=””
for string in covid strings sentence list17 
select characters
edit diffuse property
desired color=green
<header.html>
game code part2
the rest of the game code excluding answer and winner checker
java util.scanner
java.util
questions=total# of questions from covid strings17 [first-championship round]
collections.shuffle(arrays.aslist(questions)
userin.select team
import meta.
class myclass
constructor (non-concatenated)
return category
if category==math problem:
prompt
log
else:
select from multiple choice
if problem=multiple choice 
select from multiple choice
else
prompt 
log
myclass=new.myclass(concatenated)
return category
if category==math problem:
prompt
log
else:
select from multiple choice
if problem=multiple choice 
select from multiple choice
else
prompt 
log
import syntax 
substring(start,end)
<header.html>
answer checker
the feature within covid strings that allows the software to check whether a users answer is correct
for multiple choice questions in covid strings 
if selectedanswer==correct answer:
return true
else:
return false
if selectedanswer=not correct
return false
else 
return true
for math problems in covid strings
if typed answer ==correct
return true
else:
return false
if typed answer==not correct
return false
else
return true
public static main(string[]args)
int number
number=number*2
system.out print in (“the number is“ +number)
<subheading.html>
answer scanner
the feature within the covid strings answer checker that allows for confirmation of the user 
answer checker
scanner=new scanner(system.in)
string correct answer
string useranswer=scanner.nextline()
if useranswer.equals(correctanswer)
system.out.print.in(correct)
else:
system.out.printin(incorrect)
scanner.close
<header.html>
winner checker
the feature within covid strings that allows for the player to know if their team won 
check winner:
if winner==true:
log(the winner is)
else:
remain
if winner==false:
log(no winner yet)
else:
log winner
if users team wins covid strings17 
console log users team wins covid strings17 
else
remain
if users team loses covid strings17
return game over
else
remain
return filename





